kursarcoley/ingaweb/urls.py
from django.conf.urls import url
from ingaweb.views import *

urlpatterns = [
    url(r'^extraction/', ExtractionFormView),
    url(r'^batch/create/', BatchCreateView, name="BatchCreateView"),
    url(r'^batch/define/', BatchDefineView, name="BatchDefineView"),
    url(r'^batch/execute/', BatchExecuteView, name="BatchExecuteView")
]

kursarcoley/kursarcoley/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^web/', include("ingaweb.urls")),
    url(r'^update/', include("update.urls")),
    url(r'^api/', include("ingaapi.urls"))
]

kursarcoley/update/urls.py
from django.conf.urls import url
from update.views import UpdateView

urlpatterns = [
    url(r'^update/', UpdateView),
]

kursarcoley/ingaweb/models.py
import csv
from io import TextIOWrapper
import json
import traceback
from django.db import models
import inga.models as inga

class Batch(models.Model):
    input_file = models.FileField(null=True, blank=True)
    table = models.CharField(max_length=100)
    mapping = models.TextField(null=True, blank=True)
    headers = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)

    def process(self):
        mapping = json.loads(self.mapping)
        model = getattr(inga, self.table)
        errors = []

        self.input_file.file.close()
        self.input_file.file.open('rt')
        csvfile = self.input_file.file

        file = csv.DictReader(csvfile)

        for idx, row in enumerate(file):
            if idx % 100 == 0: print(idx)
            new = model()
            fields = set()
            try:
                references = {}
                for column, value in mapping.items():
                    table, field = value.split('.')
                    fields.add(row[column])

                    # If the table is ourself, just set the value
                    if table == self.table:
                        if row[column] not in ["NULL", ""]:
                            setattr(new, field, row[column])
                    else:
                        # Otherwise, we need to add it to our lookup values
                        path, table = table.rsplit(':', 1)
                        path = path.split(":")
                        local = path[0]
                        path = path[1:]
                        path.append(field)                        

                        reference_field = "__".join(path)
                        reference_value = row[column]

                        if "__" not in reference_field:
                            if local in references:
                                references[local]["table"] = table
                            else:
                                references[local] = {
                                    "table": table,
                                    "params": {}
                                }

                        if local in references:
                            references[local]["params"][reference_field] = reference_value
                        else:
                            references[local] = {
                                "params": {
                                    reference_field: reference_value
                                }
                            }
                print(fields)
                if len(fields) == 1 and "" in fields:
                    continue

                for local in references:
                    table = references[local]["table"]
                    params = references[local]["params"]
                    external = getattr(inga, table)
                    reference = external.objects.get(**params)
                    setattr(new, local, reference)

                new.save()
            except Exception as e:
                message = e.__class__.__name__ + ": " + str(e)
                problem = row
                problem["error"] = message
                errors.append(problem)
                continue

        self.complete = True
        self.save()
        self.input_file.close()

        return errors

kursarcoley/ingaweb/forms.py
from inga.models import Extraction, Chemistry, Plant, PlantSpecies
from django.apps import apps
from django import forms

INGA = apps.get_app_config('inga')
MODELS = apps.get_models()
MODELS = tuple((model.__name__, model.__name__) for model in MODELS)
BOOTSTRAP_CSS = {'class':   'form-control'}

class BootstrapForm(forms.Form):
    def __init__(self, *args, **kwargs):
            kwargs.setdefault('label_suffix', '')
            super(BootstrapForm, self).__init__(*args, **kwargs)

class ExtractionForm(BootstrapForm):
    extraction_number = forms.IntegerField(widget=forms.NumberInput(attrs=BOOTSTRAP_CSS))
    date = forms.DateField(widget=forms.DateInput(attrs=BOOTSTRAP_CSS))
    method = forms.FloatField(widget=forms.NumberInput(attrs=BOOTSTRAP_CSS))
    chemist = forms.CharField(widget=forms.TextInput(attrs=BOOTSTRAP_CSS))
    chemistry = forms.CharField(widget=forms.TextInput(attrs=BOOTSTRAP_CSS))
    plant = forms.CharField(widget=forms.TextInput(attrs=BOOTSTRAP_CSS), required=False)
    species = forms.CharField(widget=forms.TextInput(attrs=BOOTSTRAP_CSS), required=False)
    dry_weight = forms.FloatField(widget=forms.NumberInput(attrs=BOOTSTRAP_CSS), required=False)
    empty_vial_weight = forms.FloatField(widget=forms.NumberInput(attrs=BOOTSTRAP_CSS), required=False)
    final_weight = forms.FloatField(widget=forms.NumberInput(attrs=BOOTSTRAP_CSS), required=False)
    dry_marc_weight = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control', 'disabled': 'true'}), required=False)
    mass_extracted = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control', 'disabled': 'true'}), required=False)
    proportion_remaining = forms.FloatField(widget=forms.NumberInput(attrs=BOOTSTRAP_CSS), required=False)
    percent_extracted = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control', 'disabled': 'true'}), required=False)
    box = forms.CharField(widget=forms.TextInput(attrs=BOOTSTRAP_CSS), required=False)
    comments = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 2}), required=False)

    def clean(self):
        cleaned_data = super(ExtractionForm, self).clean()
        chemistry_number = cleaned_data.get("chemistry")
        plant_number = cleaned_data.get("plant")
        species_code = cleaned_data.get("species")

        try: 
            chemistry = Chemistry.objects.get(chemistry_number=chemistry_number)
            plant = chemistry.plant
            species = plant.species_code

            if (plant_number != "" and plant_number != plant.plant_number) and (species_code != "" and species_code != species.species_code):
                self.add_error(None, "There is an mismatch between the given chemistry number, plant number, and species code.")
        except Chemistry.DoesNotExist:
            self.add_error('chemistry', 'Chemistry number does not match any known chemistry.')

class BatchCreateForm(BootstrapForm):
    input_file = forms.FileField(widget=forms.FileInput(attrs=BOOTSTRAP_CSS))
    table = forms.CharField(widget=forms.Select(attrs=BOOTSTRAP_CSS, choices=MODELS))


class BatchDefineForm(BootstrapForm):
    batch = forms.IntegerField(widget=forms.HiddenInput())

    def __init__(self, model_fields, csv_headers, *args, **kwargs):
        super(BatchDefineForm, self).__init__(*args, **kwargs)
        choices = (("", ""), ) + model_fields

        for header in csv_headers:
            self.fields[header] = forms.CharField(widget=forms.Select(attrs=BOOTSTRAP_CSS, choices=choices), required=False)

kursarcoley/ingaweb/views.py
import csv
from io import TextIOWrapper
import json
from django.apps import apps
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from ingaweb.forms import ExtractionForm, BatchCreateForm, BatchDefineForm
from ingaweb.models import Batch
from inga.models import Extraction, Chemistry
from ingaweb.utilities import build_extraction, build_extraction_form

def ExtractionFormView(request):
    template = 'ingaweb/extraction_form.html'

    if request.method == 'POST':
        form = ExtractionForm(request.POST)

        if form.is_valid():
            extraction = build_extraction(form.cleaned_data)
            data = build_extraction_form(extraction)
            form = ExtractionForm(data)
        else:
            extraction = request.POST["extraction_number"]
            if extraction != "":
                try:
                    extraction = Extraction.objects.get(extraction_number=extraction)
                    data = build_extraction_form(extraction)
                    form = ExtractionForm(data)
                except Extraction.DoesNotExist:
                    pass
    else:
        form = ExtractionForm()

    return render(request, template, {'form': form})

def BatchExecuteView(request):
    if request.method == 'GET':
        return redirect('BatchCreateView')
    else:
        fields_to_ignore = ('', 'csrfmiddlewaretoken', 'batch', 'save')
        post = request.POST
        batch = Batch.objects.get(pk=post['batch'])

        mapping = {}


        for key, value in post.items():
            if key not in fields_to_ignore:
                mapping[key] = value

        batch.mapping = json.dumps(mapping)
        batch.save()

        errors = batch.process()

        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="errors.csv"'

        #headers = json.loads(batch.headers)

        batch.input_file.file.open('rt')
        csvfile = batch.input_file.file

        file = csv.DictReader(csvfile)

        writer = csv.DictWriter(response, file.fieldnames + ["error"])
        writer.writeheader()
        writer.writerows(errors)

        return response

def BatchDefineView(request):
    template = 'ingaweb/batch_define_form.html'

    if request.method == 'GET':
        return redirect('BatchCreateView')
    else:
        model = apps.get_app_config('inga').get_model(request.POST['table'])
        file = request.FILES['input_file']

        filewrapper = TextIOWrapper(file.file, encoding='utf8')
        csvdata = csv.DictReader(filewrapper)

        fields = model.names()
        headers = csvdata.fieldnames
        form = BatchDefineForm(fields, headers)

        batch = Batch()
        batch.headers = json.dumps(headers)
        batch.input_file = file
        batch.table = model.__name__
        batch.save()

        form.fields['batch'].initial = batch.id

    return render(request, template, {'form': form})


def BatchCreateView(request):
    template = 'ingaweb/batch_create_form.html'

    return render(request, template, {'form': BatchCreateForm()})

kursarcoley/ingaweb/templates/ingaweb/batch_create_form.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/south-street/jquery-ui.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <style>
            label {
                font-size: 10px
            }
             .container {
                width: 700px;
            }
        </style>
        <title>Batch Upload</title>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <h3 class="text-center">Create upload batch</h3>
            </div>
            <form action="{% url 'BatchDefineView' %}" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="row">
                    <div class="col-md-3"> </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            {{ form.input_file.errors }}
                            {{ form.input_file.label_tag }}
                            {{ form.input_file }}
                        </div>
                    </div>
                    <div class="col-md-3"> </div>
                </div>
                <div class="row">
                    <div class="col-md-3"> </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            {{ form.table.errors }}
                            {{ form.table.label_tag }}
                            {{ form.table }}
                        </div>
                    </div>
                    <div class="col-md-3"> </div>
                </div>
                <div class="row">
                    <div class="col-md-8"> </div>
                    <div class="col-md-1">
                        <input type="submit" class="btn btn-success" name="save" value="Submit" />
                    </div>
                    <div class="col-md-3"> </div>
            </form>
        </div>
    </body>
</html>

kursarcoley/ingaweb/templates/ingaweb/batch_define_form.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/south-street/jquery-ui.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <style>
            label {
                font-size: 10px
            }
             .container {
                width: 700px;
            }
        </style>
        <title>Batch Upload</title>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <h3 class="text-center">Create upload batch</h3>
            </div>
            <form action="{% url 'BatchExecuteView' %}" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="row">
                    <div class="col-md-3"> </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            {{ field.errors }}
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                    </div>
                    <div class="col-md-3"> </div>
                </div>
                {% endfor %}
                <div class="row">
                    <div class="col-md-8"> </div>
                    <div class="col-md-1">
                        <input type="submit" class="btn btn-success" name="save" value="Submit" />
                    </div>
                    <div class="col-md-3"> </div>
            </form>
        </div>
    </body>
</html>

kursarcoley/ingaweb/templates/ingaweb/extraction_form.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/south-street/jquery-ui.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <style>
            label {
                font-size: 10px
            }
             .container {
                width: 700px;
            }
        </style>
        <script>
            $(function() {
                $( "#id_date" ).datepicker();
            });
        </script>
        <title>Extraction Form</title>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <h3 class="text-center">Extraction</h3>
            </div>
            <form action="{{ request.path }}" method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.date.errors }}
                            {{ form.date.label_tag }}
                            {{ form.date }}
                        </div>
                    </div>
                    <div class="col-md-8"> </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.chemist.errors }}
                            {{ form.chemist.label_tag }}
                            {{ form.chemist }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.extraction_number.errors }}
                            {{ form.extraction_number.label_tag }}
                            {{ form.extraction_number }}
                        </div>
                    </div>
                    <div class="col-md-4"> </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.chemistry.errors }}
                            {{ form.chemistry.label_tag }}
                            {{ form.chemistry }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.species.errors }}
                            {{ form.species.label_tag }}
                            {{ form.species }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.method.errors }}
                            {{ form.method.label_tag }}
                            {{ form.method }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.dry_weight.errors }}
                            {{ form.dry_weight.label_tag }}
                            {{ form.dry_weight }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.plant.errors }}
                            {{ form.plant.label_tag }}
                            {{ form.plant }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.box.errors }}
                            {{ form.box.label_tag }}
                            {{ form.box }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.empty_vial_weight.errors }}
                            {{ form.empty_vial_weight.label_tag }}
                            {{ form.empty_vial_weight }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.final_weight.errors }}
                            {{ form.final_weight.label_tag }}
                            {{ form.final_weight }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.dry_marc_weight.errors }}
                            {{ form.dry_marc_weight.label_tag }}
                            {{ form.dry_marc_weight }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.mass_extracted.errors }}
                            {{ form.mass_extracted.label_tag }}
                            {{ form.mass_extracted }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.proportion_remaining.errors }}
                            {{ form.proportion_remaining.label_tag }}
                            {{ form.proportion_remaining }}
                        </div>
                    </div>
                    <div class="col-md-4"> </div>
                </div>
                <div class="row">
                    <div class="col-md-4"> </div>
                    <div class="col-md-4">
                            {{ form.percent_extracted.errors }}
                            {{ form.percent_extracted.label_tag }}
                            {{ form.percent_extracted }}
                    </div>
                    <div class="col-md-4"> </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            {{ form.comments.errors }}
                            {{ form.comments.label_tag }}
                            {{ form.comments }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8"> </div>
                    <div class="col-md-2">
                        <input type="reset" class="btn btn-primary" name="clear" value="Clear" onClick="window.location.reload()"/>
                    </div>
                    <div class="col-md-2">
                        <input type="submit" class="btn btn-success" name="save" value="Save/Retrieve" />
                    </div>
                </div>
            </form>
        </div>
    </body>
</html>